# Generated by Django 5.1.6 on 2025-02-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaapp', '0006_alter_mediafile_options_remove_mediafile_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
